import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = join(__dirname, "..", "data", "recipes");
mkdirSync(outDir, { recursive: true });

const ing = (name, quantity, unit, category) => ({ name, quantity, unit, category });

const recipes = [
  // ---------------- DINNERS (18) ----------------
  {
    id: "sri-lankan-chicken-curry",
    name: "Sri Lankan Chicken Curry with Rice",
    mealType: ["dinner"],
    cuisine: "sri-lankan",
    protein: "chicken",
    servings: 3,
    ingredients: [
      ing("chicken thigh, boneless", 600, "g", "protein"),
      ing("coconut milk", 400, "ml", "pantry"),
      ing("onion", 1, "unit", "vegetable"),
      ing("garlic", 3, "clove", "herb-spice"),
      ing("ginger", 1, "tbsp", "herb-spice"),
      ing("curry powder", 2, "tbsp", "pantry"),
      ing("tomato", 1, "unit", "vegetable"),
      ing("basmati rice", 300, "g", "pantry"),
      ing("curry leaves", 1, "pinch", "herb-spice"),
    ],
    steps: [
      "Cook rice.",
      "Saute onion, garlic, ginger and curry leaves until fragrant.",
      "Add chicken and curry powder, brown lightly.",
      "Add tomato and coconut milk, simmer 25 min until chicken is cooked through.",
    ],
    activeMinutes: 15,
    totalMinutes: 40,
    spiceLevel: 2,
    kaiAdjustment: "Set aside a plain portion of chicken and coconut sauce for Kai before adding chili/extra curry powder to the rest.",
    tags: ["curry", "one-pot", "batch-friendly"],
    imageQuery: "sri lankan chicken curry rice",
    batchCookFriendly: true,
  },
  {
    id: "dhal-curry-with-egg",
    name: "Dhal Curry (Parippu) with Boiled Egg",
    mealType: ["lunch", "dinner"],
    cuisine: "sri-lankan",
    protein: "lentil",
    servings: 3,
    ingredients: [
      ing("red lentils", 300, "g", "pantry"),
      ing("coconut milk", 200, "ml", "pantry"),
      ing("onion", 1, "unit", "vegetable"),
      ing("garlic", 2, "clove", "herb-spice"),
      ing("turmeric", 1, "tsp", "pantry"),
      ing("egg", 3, "unit", "protein"),
      ing("basmati rice", 250, "g", "pantry"),
      ing("mustard seeds", 1, "tsp", "pantry"),
    ],
    steps: [
      "Boil eggs, peel and set aside.",
      "Simmer lentils with turmeric and water until soft, about 15 min.",
      "Temper mustard seeds, onion and garlic in a separate pan, stir into dhal with coconut milk.",
      "Serve over rice with halved boiled eggs.",
    ],
    activeMinutes: 15,
    totalMinutes: 25,
    spiceLevel: 1,
    kaiAdjustment: "Kai's serving needs no adjustment — this dish is mild by default.",
    tags: ["curry", "one-pot", "vegetarian", "batch-friendly"],
    imageQuery: "sri lankan dhal curry egg rice",
    batchCookFriendly: true,
  },
  {
    id: "fish-ambul-thiyal",
    name: "Fish Ambul Thiyal (Sour Fish Curry)",
    mealType: ["dinner"],
    cuisine: "sri-lankan",
    protein: "fish",
    servings: 3,
    ingredients: [
      ing("firm white fish", 600, "g", "protein"),
      ing("goraka / tamarind paste", 2, "tbsp", "pantry"),
      ing("black pepper", 1, "tsp", "pantry"),
      ing("garlic", 3, "clove", "herb-spice"),
      ing("ginger", 1, "tbsp", "herb-spice"),
      ing("curry leaves", 1, "pinch", "herb-spice"),
      ing("basmati rice", 300, "g", "pantry"),
    ],
    steps: [
      "Marinate fish cubes with tamarind, pepper, garlic and ginger.",
      "Cook rice.",
      "Simmer fish gently with curry leaves in a covered pan for 30 min until sauce reduces and clings to the fish.",
    ],
    activeMinutes: 15,
    totalMinutes: 45,
    spiceLevel: 1,
    kaiAdjustment: "Remove a portion of fish before the final pepper reduction and keep it mild for Kai.",
    tags: ["curry", "simmer"],
    imageQuery: "sri lankan sour fish curry ambul thiyal",
  },
  {
    id: "kottu-roti-chicken",
    name: "Chicken Kottu Roti",
    mealType: ["dinner"],
    cuisine: "sri-lankan",
    protein: "chicken",
    servings: 3,
    ingredients: [
      ing("roti / godamba flatbread", 6, "unit", "pantry"),
      ing("chicken breast", 400, "g", "protein"),
      ing("cabbage", 200, "g", "vegetable"),
      ing("carrot", 1, "unit", "vegetable"),
      ing("onion", 1, "unit", "vegetable"),
      ing("egg", 2, "unit", "protein"),
      ing("curry powder", 1, "tbsp", "pantry"),
      ing("soy sauce", 1, "tbsp", "pantry"),
    ],
    steps: [
      "Slice roti into strips.",
      "Stir-fry chicken with onion and curry powder until cooked.",
      "Add cabbage and carrot, stir-fry until just tender.",
      "Push to one side, scramble egg in, then toss everything with roti strips and soy sauce, chopping and mixing constantly.",
    ],
    activeMinutes: 25,
    totalMinutes: 30,
    spiceLevel: 2,
    kaiAdjustment: "Cook a small plain batch of chopped roti, chicken and veg for Kai before adding curry powder and chili to the rest.",
    tags: ["constant-stir", "stir-fry", "quick"],
    imageQuery: "sri lankan chicken kottu roti",
  },
  {
    id: "thai-basil-chicken",
    name: "Thai Basil Chicken (Pad Kra Pao)",
    mealType: ["dinner"],
    cuisine: "thai",
    protein: "chicken",
    servings: 3,
    ingredients: [
      ing("chicken mince", 500, "g", "protein"),
      ing("thai basil", 1, "cup", "vegetable"),
      ing("garlic", 4, "clove", "herb-spice"),
      ing("long red chili", 2, "unit", "vegetable"),
      ing("soy sauce", 2, "tbsp", "pantry"),
      ing("oyster sauce", 2, "tbsp", "pantry"),
      ing("fish sauce", 1, "tbsp", "pantry"),
      ing("jasmine rice", 300, "g", "pantry"),
      ing("egg", 3, "unit", "protein"),
    ],
    steps: [
      "Cook rice.",
      "Fry egg sunny-side up per person, set aside.",
      "Stir-fry garlic and chili, add mince and cook through.",
      "Add sauces and basil, toss until wilted. Serve over rice topped with fried egg.",
    ],
    activeMinutes: 25,
    totalMinutes: 25,
    spiceLevel: 3,
    kaiAdjustment: "Cook Kai's mince portion before adding chili, then season the rest of the pan for the adults.",
    tags: ["constant-stir", "stir-fry", "quick"],
    imageQuery: "thai basil chicken pad kra pao",
  },
  {
    id: "thai-green-curry-prawn",
    name: "Thai Green Curry with Prawns",
    mealType: ["dinner"],
    cuisine: "thai",
    protein: "prawn",
    servings: 3,
    ingredients: [
      ing("prawns, peeled", 500, "g", "protein"),
      ing("green curry paste", 3, "tbsp", "pantry"),
      ing("coconut milk", 400, "ml", "pantry"),
      ing("eggplant", 1, "unit", "vegetable"),
      ing("green beans", 150, "g", "vegetable"),
      ing("fish sauce", 1, "tbsp", "pantry"),
      ing("jasmine rice", 300, "g", "pantry"),
      ing("thai basil", 0.5, "cup", "vegetable"),
    ],
    steps: [
      "Cook rice.",
      "Fry curry paste in a splash of coconut milk until fragrant.",
      "Add remaining coconut milk, eggplant and beans, simmer 10 min.",
      "Add prawns and fish sauce, cook 5 min until prawns are pink. Finish with basil.",
    ],
    activeMinutes: 20,
    totalMinutes: 35,
    spiceLevel: 2,
    kaiAdjustment: "Reserve a small portion of prawns and vegetables in plain coconut milk before stirring in the curry paste.",
    tags: ["curry", "one-pot"],
    imageQuery: "thai green curry prawns",
  },
  {
    id: "chinese-egg-fried-rice-pork",
    name: "Egg Fried Rice with Char Siu-Style Pork",
    mealType: ["lunch", "dinner"],
    cuisine: "chinese",
    protein: "pork",
    servings: 3,
    ingredients: [
      ing("pork fillet", 400, "g", "protein"),
      ing("hoisin sauce", 2, "tbsp", "pantry"),
      ing("soy sauce", 2, "tbsp", "pantry"),
      ing("cooked rice (day-old)", 500, "g", "pantry"),
      ing("egg", 3, "unit", "protein"),
      ing("spring onion", 3, "unit", "vegetable"),
      ing("frozen peas", 100, "g", "vegetable"),
      ing("carrot", 1, "unit", "vegetable"),
    ],
    steps: [
      "Marinate pork in hoisin and soy, pan-roast until cooked through, then slice.",
      "Scramble egg in a hot wok, remove.",
      "Stir-fry rice, peas and carrot, add egg back in with spring onion and a splash of soy sauce.",
      "Top with sliced pork.",
    ],
    activeMinutes: 25,
    totalMinutes: 30,
    spiceLevel: 0,
    kaiAdjustment: "No adjustment needed — mild dish, just chop pork smaller for Kai.",
    tags: ["stir-fry", "quick", "batch-friendly"],
    imageQuery: "chinese egg fried rice char siu pork",
    batchCookFriendly: true,
  },
  {
    id: "beef-broccoli-stir-fry",
    name: "Beef and Broccoli Stir-Fry",
    mealType: ["dinner"],
    cuisine: "chinese",
    protein: "beef",
    servings: 3,
    ingredients: [
      ing("beef strips", 500, "g", "protein"),
      ing("broccoli", 300, "g", "vegetable"),
      ing("garlic", 3, "clove", "herb-spice"),
      ing("soy sauce", 2, "tbsp", "pantry"),
      ing("oyster sauce", 2, "tbsp", "pantry"),
      ing("cornflour", 1, "tsp", "pantry"),
      ing("jasmine rice", 300, "g", "pantry"),
    ],
    steps: [
      "Cook rice.",
      "Blanch broccoli briefly, set aside.",
      "Sear beef strips over high heat in batches, set aside.",
      "Stir-fry garlic, return beef and broccoli, add sauces and cornflour slurry, toss until glossy.",
    ],
    activeMinutes: 25,
    totalMinutes: 25,
    spiceLevel: 0,
    kaiAdjustment: "No adjustment needed — mild dish, chop beef finely for Kai.",
    tags: ["constant-stir", "stir-fry", "quick"],
    imageQuery: "beef broccoli stir fry",
  },
  {
    id: "teriyaki-salmon",
    name: "Teriyaki Salmon with Steamed Rice",
    mealType: ["dinner"],
    cuisine: "japanese",
    protein: "fish",
    servings: 3,
    ingredients: [
      ing("salmon fillet", 600, "g", "protein"),
      ing("soy sauce", 3, "tbsp", "pantry"),
      ing("honey", 2, "tbsp", "pantry"),
      ing("rice wine", 2, "tbsp", "pantry"),
      ing("jasmine rice", 300, "g", "pantry"),
      ing("broccolini", 200, "g", "vegetable"),
      ing("sesame oil", 1, "tsp", "pantry"),
    ],
    steps: [
      "Mix soy sauce, honey and rice wine for teriyaki glaze.",
      "Cook rice.",
      "Bake salmon at 200C brushed with glaze for 15-18 min, brushing once more halfway.",
      "Steam broccolini and drizzle with sesame oil.",
    ],
    activeMinutes: 10,
    totalMinutes: 30,
    spiceLevel: 0,
    kaiAdjustment: "No adjustment needed — mild, flake and check for bones for Kai.",
    tags: ["oven", "low-active"],
    imageQuery: "teriyaki salmon rice",
  },
  {
    id: "chicken-katsu",
    name: "Chicken Katsu with Rice",
    mealType: ["dinner"],
    cuisine: "japanese",
    protein: "chicken",
    servings: 3,
    ingredients: [
      ing("chicken breast", 500, "g", "protein"),
      ing("panko breadcrumbs", 150, "g", "pantry"),
      ing("egg", 2, "unit", "protein"),
      ing("cornflour", 2, "tbsp", "pantry"),
      ing("jasmine rice", 300, "g", "pantry"),
      ing("cabbage", 150, "g", "vegetable"),
      ing("tonkatsu sauce", 3, "tbsp", "pantry"),
    ],
    steps: [
      "Cook rice and shred cabbage.",
      "Crumb chicken breast: cornflour, then egg, then panko.",
      "Pan-fry until golden and cooked through, about 5 min per side.",
      "Slice and serve over rice with cabbage and tonkatsu sauce.",
    ],
    activeMinutes: 30,
    totalMinutes: 35,
    spiceLevel: 0,
    kaiAdjustment: "No adjustment needed — mild, slice into small pieces for Kai.",
    tags: ["deep-fry", "constant-stir"],
    imageQuery: "chicken katsu rice",
  },
  {
    id: "vietnamese-chicken-pho",
    name: "Vietnamese Chicken Pho",
    mealType: ["dinner"],
    cuisine: "vietnamese",
    protein: "chicken",
    servings: 3,
    ingredients: [
      ing("chicken thigh, bone-in", 600, "g", "protein"),
      ing("rice noodles", 300, "g", "pantry"),
      ing("ginger", 1, "unit", "herb-spice"),
      ing("onion", 1, "unit", "vegetable"),
      ing("star anise", 2, "unit", "herb-spice"),
      ing("cinnamon stick", 1, "unit", "pantry"),
      ing("fish sauce", 2, "tbsp", "pantry"),
      ing("bean sprouts", 100, "g", "vegetable"),
      ing("spring onion", 3, "unit", "vegetable"),
    ],
    steps: [
      "Char ginger and onion, simmer with chicken, star anise and cinnamon for 35 min to build broth.",
      "Remove chicken, shred meat once cool enough to handle.",
      "Soak rice noodles until soft.",
      "Season broth with fish sauce, assemble bowls with noodles, chicken, sprouts and spring onion.",
    ],
    activeMinutes: 15,
    totalMinutes: 45,
    spiceLevel: 0,
    kaiAdjustment: "No adjustment needed — serve broth slightly cooled for Kai and skip any chili/lime added at the table.",
    tags: ["simmer", "low-active"],
    imageQuery: "vietnamese chicken pho",
  },
  {
    id: "bun-cha-pork",
    name: "Bun Cha (Vermicelli with Grilled Pork)",
    mealType: ["dinner"],
    cuisine: "vietnamese",
    protein: "pork",
    servings: 3,
    ingredients: [
      ing("pork mince", 500, "g", "protein"),
      ing("rice vermicelli noodles", 300, "g", "pantry"),
      ing("fish sauce", 2, "tbsp", "pantry"),
      ing("lime", 1, "unit", "vegetable"),
      ing("carrot", 1, "unit", "vegetable"),
      ing("cucumber", 1, "unit", "vegetable"),
      ing("lettuce", 1, "unit", "vegetable"),
      ing("garlic", 2, "clove", "herb-spice"),
    ],
    steps: [
      "Form pork mince into small patties, marinate with fish sauce and garlic.",
      "Soak noodles, pickle sliced carrot briefly in lime juice.",
      "Pan-fry or grill patties until browned and cooked through.",
      "Serve noodles topped with patties, herbs, lettuce and cucumber, with dipping sauce.",
    ],
    activeMinutes: 25,
    totalMinutes: 35,
    spiceLevel: 1,
    kaiAdjustment: "Kai's patties can be served without chili in the dipping sauce.",
    tags: ["grill", "constant-stir"],
    imageQuery: "vietnamese bun cha grilled pork vermicelli",
  },
  {
    id: "korean-bulgogi-beef",
    name: "Korean Bulgogi Beef with Rice",
    mealType: ["dinner"],
    cuisine: "korean",
    protein: "beef",
    servings: 3,
    ingredients: [
      ing("beef sirloin, thin sliced", 500, "g", "protein"),
      ing("soy sauce", 3, "tbsp", "pantry"),
      ing("brown sugar", 2, "tbsp", "pantry"),
      ing("garlic", 3, "clove", "herb-spice"),
      ing("sesame oil", 1, "tbsp", "pantry"),
      ing("jasmine rice", 300, "g", "pantry"),
      ing("carrot", 1, "unit", "vegetable"),
      ing("spring onion", 2, "unit", "vegetable"),
    ],
    steps: [
      "Marinate beef with soy sauce, sugar, garlic and sesame oil for at least 10 min.",
      "Cook rice.",
      "Stir-fry beef and carrot over high heat in batches until caramelised.",
      "Serve over rice topped with spring onion.",
    ],
    activeMinutes: 20,
    totalMinutes: 30,
    spiceLevel: 0,
    kaiAdjustment: "No adjustment needed — mild, chop finely for Kai.",
    tags: ["constant-stir", "stir-fry", "quick"],
    imageQuery: "korean bulgogi beef rice",
  },
  {
    id: "korean-baked-chicken-thighs",
    name: "Korean-Style Baked Chicken Thighs",
    mealType: ["dinner"],
    cuisine: "korean",
    protein: "chicken",
    servings: 3,
    ingredients: [
      ing("chicken thigh, bone-in", 800, "g", "protein"),
      ing("gochujang", 2, "tbsp", "pantry"),
      ing("soy sauce", 2, "tbsp", "pantry"),
      ing("honey", 2, "tbsp", "pantry"),
      ing("garlic", 3, "clove", "herb-spice"),
      ing("jasmine rice", 300, "g", "pantry"),
      ing("broccoli", 200, "g", "vegetable"),
    ],
    steps: [
      "Mix gochujang, soy sauce, honey and garlic, coat chicken thighs.",
      "Bake at 200C for 35-40 min until sticky and cooked through.",
      "Cook rice and steam broccoli while chicken bakes.",
    ],
    activeMinutes: 10,
    totalMinutes: 45,
    spiceLevel: 2,
    kaiAdjustment: "Set aside plain chicken thighs for Kai before glazing the rest with gochujang.",
    tags: ["oven", "low-active"],
    imageQuery: "korean baked chicken thighs gochujang",
  },
  {
    id: "malaysian-chicken-laksa",
    name: "Malaysian Chicken Curry Laksa",
    mealType: ["dinner"],
    cuisine: "malaysian",
    protein: "chicken",
    servings: 3,
    ingredients: [
      ing("chicken thigh, boneless", 500, "g", "protein"),
      ing("laksa paste", 4, "tbsp", "pantry"),
      ing("coconut milk", 400, "ml", "pantry"),
      ing("rice noodles", 300, "g", "pantry"),
      ing("bean sprouts", 100, "g", "vegetable"),
      ing("fish sauce", 1, "tbsp", "pantry"),
      ing("lime", 1, "unit", "vegetable"),
    ],
    steps: [
      "Fry laksa paste until fragrant.",
      "Add coconut milk and stock/water, simmer with chicken until cooked, about 15 min.",
      "Soak rice noodles until soft.",
      "Assemble bowls: noodles, broth, chicken, bean sprouts, lime wedge.",
    ],
    activeMinutes: 20,
    totalMinutes: 40,
    spiceLevel: 2,
    kaiAdjustment: "Reserve a portion of chicken and coconut broth for Kai before adding the full amount of laksa paste.",
    tags: ["curry", "one-pot"],
    imageQuery: "malaysian chicken curry laksa",
  },
  {
    id: "indian-butter-chicken",
    name: "Butter Chicken with Rice",
    mealType: ["dinner"],
    cuisine: "indian",
    protein: "chicken",
    servings: 3,
    ingredients: [
      ing("chicken thigh, boneless", 600, "g", "protein"),
      ing("tomato paste", 2, "tbsp", "pantry"),
      ing("cream", 150, "ml", "dairy"),
      ing("butter", 30, "g", "dairy"),
      ing("garam masala", 1, "tbsp", "pantry"),
      ing("garlic", 3, "clove", "herb-spice"),
      ing("ginger", 1, "tbsp", "herb-spice"),
      ing("basmati rice", 300, "g", "pantry"),
    ],
    steps: [
      "Cook rice.",
      "Saute garlic, ginger and garam masala in butter.",
      "Add chicken, brown lightly, then add tomato paste and simmer 15 min.",
      "Stir through cream, simmer 5 more minutes until chicken is cooked through.",
    ],
    activeMinutes: 20,
    totalMinutes: 35,
    spiceLevel: 1,
    kaiAdjustment: "Reserve a mild portion of chicken and sauce for Kai before adding extra garam masala/chili to the rest.",
    tags: ["curry", "one-pot", "batch-friendly"],
    imageQuery: "butter chicken curry rice",
    batchCookFriendly: true,
  },
  {
    id: "chicken-tikka-tray-bake",
    name: "Chicken Tikka Tray Bake",
    mealType: ["dinner"],
    cuisine: "indian",
    protein: "chicken",
    servings: 3,
    ingredients: [
      ing("chicken thigh, boneless", 600, "g", "protein"),
      ing("yoghurt", 150, "g", "dairy"),
      ing("tikka spice mix", 2, "tbsp", "pantry"),
      ing("capsicum", 2, "unit", "vegetable"),
      ing("red onion", 1, "unit", "vegetable"),
      ing("basmati rice", 300, "g", "pantry"),
    ],
    steps: [
      "Marinate chicken in yoghurt and tikka spice, ideally 20+ min.",
      "Spread chicken, capsicum and onion on a tray, roast at 200C for 25-30 min.",
      "Cook rice while the tray bakes.",
    ],
    activeMinutes: 12,
    totalMinutes: 40,
    spiceLevel: 1,
    kaiAdjustment: "Set aside plain chicken pieces before marinating the rest with tikka spice.",
    tags: ["oven", "low-active"],
    imageQuery: "chicken tikka tray bake",
  },
  {
    id: "tofu-vegetable-stir-fry",
    name: "Tofu and Vegetable Stir-Fry",
    mealType: ["dinner"],
    cuisine: "chinese",
    protein: "tofu",
    servings: 3,
    ingredients: [
      ing("firm tofu", 400, "g", "protein"),
      ing("broccoli", 150, "g", "vegetable"),
      ing("carrot", 1, "unit", "vegetable"),
      ing("snow peas", 100, "g", "vegetable"),
      ing("soy sauce", 2, "tbsp", "pantry"),
      ing("oyster sauce", 2, "tbsp", "pantry"),
      ing("garlic", 2, "clove", "herb-spice"),
      ing("jasmine rice", 300, "g", "pantry"),
    ],
    steps: [
      "Cook rice.",
      "Pan-fry cubed tofu until golden on all sides, set aside.",
      "Stir-fry garlic and vegetables until just tender.",
      "Return tofu, add sauces and toss to combine.",
    ],
    activeMinutes: 20,
    totalMinutes: 25,
    spiceLevel: 0,
    kaiAdjustment: "No adjustment needed — mild vegetarian dish.",
    tags: ["constant-stir", "stir-fry", "quick", "vegetarian"],
    imageQuery: "tofu vegetable stir fry",
  },

  // ---------------- LUNCHES (8, some dual-tagged above already count) ----------------
  {
    id: "prawn-noodle-salad",
    name: "Prawn Noodle Salad",
    mealType: ["lunch"],
    cuisine: "vietnamese",
    protein: "prawn",
    servings: 3,
    ingredients: [
      ing("prawns, peeled", 400, "g", "protein"),
      ing("rice vermicelli noodles", 250, "g", "pantry"),
      ing("cucumber", 1, "unit", "vegetable"),
      ing("carrot", 1, "unit", "vegetable"),
      ing("lettuce", 1, "unit", "vegetable"),
      ing("fish sauce", 2, "tbsp", "pantry"),
      ing("lime", 1, "unit", "vegetable"),
    ],
    steps: [
      "Cook noodles and cool under water.",
      "Pan-fry or steam prawns until pink, about 4 min.",
      "Toss noodles with shredded vegetables, top with prawns.",
      "Dress with fish sauce and lime juice.",
    ],
    activeMinutes: 20,
    totalMinutes: 20,
    spiceLevel: 0,
    kaiAdjustment: "No adjustment needed — serve dressing on the side for Kai.",
    tags: ["salad", "quick", "no-cook-mostly"],
    imageQuery: "vietnamese prawn noodle salad",
  },
  {
    id: "chicken-fried-rice-lunch",
    name: "Chicken Fried Rice",
    mealType: ["lunch"],
    cuisine: "chinese",
    protein: "chicken",
    servings: 3,
    ingredients: [
      ing("chicken breast", 350, "g", "protein"),
      ing("cooked rice (day-old)", 500, "g", "pantry"),
      ing("egg", 2, "unit", "protein"),
      ing("frozen peas", 100, "g", "vegetable"),
      ing("carrot", 1, "unit", "vegetable"),
      ing("soy sauce", 2, "tbsp", "pantry"),
      ing("spring onion", 2, "unit", "vegetable"),
    ],
    steps: [
      "Dice and cook chicken until browned.",
      "Scramble egg, remove.",
      "Stir-fry rice, peas and carrot, return chicken and egg, season with soy sauce.",
    ],
    activeMinutes: 20,
    totalMinutes: 20,
    spiceLevel: 0,
    kaiAdjustment: "No adjustment needed — mild and easy for Kai.",
    tags: ["stir-fry", "quick", "batch-friendly"],
    imageQuery: "chicken fried rice",
    batchCookFriendly: true,
  },
  {
    id: "tofu-noodle-soup-lunch",
    name: "Miso Tofu Noodle Soup",
    mealType: ["lunch"],
    cuisine: "japanese",
    protein: "tofu",
    servings: 3,
    ingredients: [
      ing("firm tofu", 300, "g", "protein"),
      ing("miso paste", 3, "tbsp", "pantry"),
      ing("egg noodles", 250, "g", "pantry"),
      ing("spring onion", 2, "unit", "vegetable"),
      ing("bok choy", 150, "g", "vegetable"),
    ],
    steps: [
      "Bring water/stock to a simmer, whisk in miso paste.",
      "Add noodles and bok choy, simmer 5 min.",
      "Add cubed tofu, warm through, top with spring onion.",
    ],
    activeMinutes: 15,
    totalMinutes: 20,
    spiceLevel: 0,
    kaiAdjustment: "No adjustment needed — mild broth suits Kai.",
    tags: ["simmer", "quick", "vegetarian"],
    imageQuery: "miso tofu noodle soup",
  },
  {
    id: "egg-hoppers-sambal",
    name: "Egg Hoppers with Coconut Sambal",
    mealType: ["breakfast", "lunch"],
    cuisine: "sri-lankan",
    protein: "egg",
    servings: 3,
    ingredients: [
      ing("hopper batter (rice flour, coconut milk)", 400, "ml", "pantry"),
      ing("egg", 3, "unit", "protein"),
      ing("desiccated coconut", 100, "g", "pantry"),
      ing("red onion", 0.5, "unit", "vegetable"),
      ing("lime", 0.5, "unit", "vegetable"),
      ing("chili flakes", 1, "tsp", "pantry"),
    ],
    steps: [
      "Heat hopper pan, swirl in batter to form a bowl shape.",
      "Crack an egg into the centre, cover and cook until white sets.",
      "Mix coconut, onion, lime and chili flakes for sambal.",
      "Serve hoppers with sambal on the side.",
    ],
    activeMinutes: 20,
    totalMinutes: 25,
    spiceLevel: 2,
    kaiAdjustment: "Serve Kai's hopper with plain coconut (no chili flakes) instead of the spiced sambal.",
    tags: ["quick"],
    imageQuery: "sri lankan egg hoppers coconut sambal",
  },
  {
    id: "vegetable-fried-noodles-lunch",
    name: "Vegetable and Egg Fried Noodles",
    mealType: ["lunch"],
    cuisine: "chinese",
    protein: "egg",
    servings: 3,
    ingredients: [
      ing("egg noodles", 300, "g", "pantry"),
      ing("egg", 3, "unit", "protein"),
      ing("cabbage", 150, "g", "vegetable"),
      ing("carrot", 1, "unit", "vegetable"),
      ing("bean sprouts", 100, "g", "vegetable"),
      ing("soy sauce", 2, "tbsp", "pantry"),
      ing("sesame oil", 1, "tsp", "pantry"),
    ],
    steps: [
      "Cook noodles, drain.",
      "Scramble egg, remove.",
      "Stir-fry vegetables until just tender, add noodles and egg back in.",
      "Season with soy sauce and a drizzle of sesame oil.",
    ],
    activeMinutes: 18,
    totalMinutes: 20,
    spiceLevel: 0,
    kaiAdjustment: "No adjustment needed — mild vegetarian dish.",
    tags: ["stir-fry", "quick", "vegetarian"],
    imageQuery: "vegetable egg fried noodles",
  },
  {
    id: "korean-bibimbap-beef-lunch",
    name: "Beef Bibimbap Bowl",
    mealType: ["lunch"],
    cuisine: "korean",
    protein: "beef",
    servings: 3,
    ingredients: [
      ing("beef mince", 400, "g", "protein"),
      ing("jasmine rice", 300, "g", "pantry"),
      ing("carrot", 1, "unit", "vegetable"),
      ing("spinach", 100, "g", "vegetable"),
      ing("egg", 3, "unit", "protein"),
      ing("soy sauce", 2, "tbsp", "pantry"),
      ing("sesame oil", 1, "tbsp", "pantry"),
    ],
    steps: [
      "Cook rice.",
      "Brown beef mince with soy sauce and a little sesame oil.",
      "Quickly saute carrot and spinach separately.",
      "Fry an egg per person, assemble bowls with rice, beef, vegetables and egg on top.",
    ],
    activeMinutes: 22,
    totalMinutes: 25,
    spiceLevel: 0,
    kaiAdjustment: "No adjustment needed — mild, chop beef finely for Kai.",
    tags: ["stir-fry", "quick"],
    imageQuery: "korean beef bibimbap bowl",
  },
  {
    id: "chickpea-lentil-rice-bowl-lunch",
    name: "Spiced Lentil and Rice Bowl",
    mealType: ["lunch"],
    cuisine: "indian",
    protein: "lentil",
    servings: 3,
    ingredients: [
      ing("red lentils", 250, "g", "pantry"),
      ing("basmati rice", 250, "g", "pantry"),
      ing("cumin seeds", 1, "tsp", "pantry"),
      ing("turmeric", 0.5, "tsp", "pantry"),
      ing("spinach", 100, "g", "vegetable"),
      ing("tomato", 1, "unit", "vegetable"),
    ],
    steps: [
      "Cook rice.",
      "Simmer lentils with turmeric until soft, about 15 min.",
      "Temper cumin seeds in a little oil, stir into lentils with chopped tomato and spinach.",
      "Serve lentils over rice.",
    ],
    activeMinutes: 15,
    totalMinutes: 25,
    spiceLevel: 0,
    kaiAdjustment: "No adjustment needed — mild vegetarian dish.",
    tags: ["one-pot", "quick", "vegetarian"],
    imageQuery: "spiced lentil rice bowl",
  },
  {
    id: "prawn-fried-rice-lunch",
    name: "Prawn Fried Rice",
    mealType: ["lunch"],
    cuisine: "chinese",
    protein: "prawn",
    servings: 3,
    ingredients: [
      ing("prawns, peeled", 350, "g", "protein"),
      ing("cooked rice (day-old)", 500, "g", "pantry"),
      ing("egg", 2, "unit", "protein"),
      ing("frozen peas", 100, "g", "vegetable"),
      ing("spring onion", 2, "unit", "vegetable"),
      ing("soy sauce", 2, "tbsp", "pantry"),
    ],
    steps: [
      "Cook prawns quickly until pink, set aside.",
      "Scramble egg, remove.",
      "Stir-fry rice and peas, return egg and prawns, season with soy sauce and spring onion.",
    ],
    activeMinutes: 18,
    totalMinutes: 18,
    spiceLevel: 0,
    kaiAdjustment: "No adjustment needed — mild and easy for Kai.",
    tags: ["stir-fry", "quick", "batch-friendly"],
    imageQuery: "prawn fried rice",
    batchCookFriendly: true,
  },

  // ---------------- BREAKFASTS (8) ----------------
  {
    id: "congee-shredded-chicken",
    name: "Chicken Congee",
    mealType: ["breakfast"],
    cuisine: "chinese",
    protein: "chicken",
    servings: 3,
    ingredients: [
      ing("jasmine rice", 150, "g", "pantry"),
      ing("chicken breast", 250, "g", "protein"),
      ing("ginger", 1, "tbsp", "herb-spice"),
      ing("spring onion", 2, "unit", "vegetable"),
      ing("soy sauce", 1, "tbsp", "pantry"),
    ],
    steps: [
      "Simmer rice in plenty of water with ginger for 35-40 min, stirring occasionally, until porridge-like.",
      "Poach chicken separately, shred once cooked.",
      "Stir chicken through congee, top with spring onion and a dash of soy sauce.",
    ],
    activeMinutes: 10,
    totalMinutes: 45,
    spiceLevel: 0,
    kaiAdjustment: "No adjustment needed — naturally soft and mild for Kai.",
    tags: ["simmer", "low-active"],
    imageQuery: "chicken congee breakfast",
  },
  {
    id: "vegetable-omelette-rice",
    name: "Vegetable Omelette with Rice",
    mealType: ["breakfast"],
    cuisine: "chinese",
    protein: "egg",
    servings: 3,
    ingredients: [
      ing("egg", 6, "unit", "protein"),
      ing("carrot", 1, "unit", "vegetable"),
      ing("spring onion", 2, "unit", "vegetable"),
      ing("jasmine rice", 250, "g", "pantry"),
      ing("soy sauce", 1, "tbsp", "pantry"),
    ],
    steps: [
      "Cook rice.",
      "Whisk eggs with finely diced carrot and spring onion.",
      "Cook omelette in a non-stick pan until just set.",
      "Serve sliced over rice with a dash of soy sauce.",
    ],
    activeMinutes: 15,
    totalMinutes: 20,
    spiceLevel: 0,
    kaiAdjustment: "No adjustment needed.",
    tags: ["quick", "vegetarian"],
    imageQuery: "vegetable omelette rice breakfast",
  },
  {
    id: "string-hoppers-sambal",
    name: "String Hoppers with Coconut Sambal and Egg Curry",
    mealType: ["breakfast"],
    cuisine: "sri-lankan",
    protein: "egg",
    servings: 3,
    ingredients: [
      ing("string hoppers (idiyappam)", 12, "unit", "pantry"),
      ing("egg", 4, "unit", "protein"),
      ing("coconut milk", 200, "ml", "pantry"),
      ing("desiccated coconut", 80, "g", "pantry"),
      ing("red onion", 0.5, "unit", "vegetable"),
      ing("chili flakes", 1, "tsp", "pantry"),
      ing("curry powder", 1, "tsp", "pantry"),
    ],
    steps: [
      "Steam or warm string hoppers.",
      "Boil eggs, halve, simmer briefly in coconut milk and curry powder for a light egg curry.",
      "Mix coconut, onion and chili flakes for sambal.",
      "Serve string hoppers with sambal and egg curry on the side.",
    ],
    activeMinutes: 20,
    totalMinutes: 25,
    spiceLevel: 2,
    kaiAdjustment: "Serve Kai's string hoppers with plain coconut and egg curry made before adding chili flakes.",
    tags: ["quick"],
    imageQuery: "sri lankan string hoppers sambal egg curry",
  },
  {
    id: "japanese-tamagoyaki-rice",
    name: "Tamagoyaki (Rolled Omelette) with Rice",
    mealType: ["breakfast"],
    cuisine: "japanese",
    protein: "egg",
    servings: 3,
    ingredients: [
      ing("egg", 6, "unit", "protein"),
      ing("soy sauce", 1, "tbsp", "pantry"),
      ing("rice wine", 1, "tbsp", "pantry"),
      ing("jasmine rice", 250, "g", "pantry"),
      ing("spring onion", 1, "unit", "vegetable"),
    ],
    steps: [
      "Cook rice.",
      "Whisk eggs with soy sauce and rice wine.",
      "Cook in thin layers in a rectangular pan, rolling each layer as it sets.",
      "Slice and serve with rice.",
    ],
    activeMinutes: 15,
    totalMinutes: 15,
    spiceLevel: 0,
    kaiAdjustment: "No adjustment needed.",
    tags: ["quick", "vegetarian"],
    imageQuery: "tamagoyaki rolled omelette rice",
  },
  {
    id: "chicken-congee-alt-mushroom",
    name: "Chicken and Mushroom Congee",
    mealType: ["breakfast"],
    cuisine: "chinese",
    protein: "chicken",
    servings: 3,
    ingredients: [
      ing("jasmine rice", 150, "g", "pantry"),
      ing("chicken thigh, boneless", 250, "g", "protein"),
      ing("shiitake mushroom", 100, "g", "vegetable"),
      ing("ginger", 1, "tbsp", "herb-spice"),
      ing("spring onion", 2, "unit", "vegetable"),
    ],
    steps: [
      "Simmer rice in plenty of water with ginger and sliced mushroom for 35-40 min.",
      "Add diced chicken in the last 10 min to poach through.",
      "Top with spring onion to serve.",
    ],
    activeMinutes: 10,
    totalMinutes: 45,
    spiceLevel: 0,
    kaiAdjustment: "No adjustment needed — naturally soft and mild for Kai.",
    tags: ["simmer", "low-active"],
    imageQuery: "chicken mushroom congee",
  },
  {
    id: "coconut-roti-scrambled-egg",
    name: "Coconut Roti with Scrambled Egg",
    mealType: ["breakfast"],
    cuisine: "sri-lankan",
    protein: "egg",
    servings: 3,
    ingredients: [
      ing("coconut roti", 6, "unit", "pantry"),
      ing("egg", 6, "unit", "protein"),
      ing("red onion", 0.5, "unit", "vegetable"),
      ing("curry leaves", 1, "pinch", "herb-spice"),
    ],
    steps: [
      "Warm roti in a dry pan.",
      "Saute onion and curry leaves briefly.",
      "Scramble eggs through the onion mixture until just set.",
      "Serve with warm roti.",
    ],
    activeMinutes: 15,
    totalMinutes: 15,
    spiceLevel: 0,
    kaiAdjustment: "No adjustment needed.",
    tags: ["quick", "vegetarian"],
    imageQuery: "sri lankan coconut roti scrambled egg",
  },
  {
    id: "thai-style-fried-rice-breakfast",
    name: "Thai-Style Egg and Vegetable Fried Rice",
    mealType: ["breakfast", "lunch"],
    cuisine: "thai",
    protein: "egg",
    servings: 3,
    ingredients: [
      ing("cooked rice (day-old)", 450, "g", "pantry"),
      ing("egg", 4, "unit", "protein"),
      ing("carrot", 1, "unit", "vegetable"),
      ing("frozen peas", 80, "g", "vegetable"),
      ing("soy sauce", 1, "tbsp", "pantry"),
      ing("spring onion", 2, "unit", "vegetable"),
    ],
    steps: [
      "Scramble eggs, remove.",
      "Stir-fry rice with carrot and peas.",
      "Return egg, season with soy sauce, top with spring onion.",
    ],
    activeMinutes: 15,
    totalMinutes: 15,
    spiceLevel: 0,
    kaiAdjustment: "No adjustment needed.",
    tags: ["stir-fry", "quick", "vegetarian"],
    imageQuery: "thai style egg vegetable fried rice",
  },
  {
    id: "vietnamese-banh-mi-egg",
    name: "Vietnamese-Style Egg Baguette (Banh Mi)",
    mealType: ["breakfast"],
    cuisine: "vietnamese",
    protein: "egg",
    servings: 3,
    ingredients: [
      ing("baguette", 3, "unit", "pantry"),
      ing("egg", 6, "unit", "protein"),
      ing("carrot", 1, "unit", "vegetable"),
      ing("cucumber", 1, "unit", "vegetable"),
      ing("soy sauce", 1, "tbsp", "pantry"),
      ing("mayonnaise", 2, "tbsp", "dairy"),
    ],
    steps: [
      "Quick-pickle shredded carrot briefly.",
      "Fry eggs to your liking.",
      "Split baguettes, spread mayonnaise, fill with egg, carrot and cucumber, drizzle with soy sauce.",
    ],
    activeMinutes: 15,
    totalMinutes: 15,
    spiceLevel: 0,
    kaiAdjustment: "No adjustment needed — serve Kai's portion open-faced without chili.",
    tags: ["quick", "no-cook-mostly"],
    imageQuery: "vietnamese banh mi egg baguette",
  },
];

for (const r of recipes) {
  writeFileSync(join(outDir, `${r.id}.json`), JSON.stringify(r, null, 2) + "\n");
}

console.log(`Wrote ${recipes.length} recipe files to ${outDir}`);
